### ISSUE TITLE
Automatically update copyright dates

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/ods-charts#13]
### Description

This repository contains legal headers (or other files) containing the current year.

The idea in this issue would be to create a JS script allowing to update these years automatically.

**Comment by nbossard** [comment]
Vim is your forever friend : 

1) open project root folder in vim or neovim
2) type `vimgrep /2023 Orange/ src/**/*.ts`
3) check "quick fix" list has been correctly populated using `:copen`
4) replace all instances using `:cdo %s/2023 Orange/2024 Orange`
