### ISSUE TITLE
Error using boosted 4 tooltip in an Angular project

### ISSUE THREAD

**Issue by jacques-lebourgeois** [Orange-OpenSource/ods-charts#276]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/ods-charts/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/ods-charts/blob/main/CONTRIBUTING.md)

### Describe the issue

Using tooltip managed by ODS Charts with Boosted 4 renderer fails 

```
    // Register the externalization of the tooltip/popup
    this.themeManager.externalizePopover(
      {},
      ODSCharts.ODSChartsPopoverManagers.BOOSTED4
    );
```

### Reduced test cases

we got the error console

```
ods-charts.js:2782 ReferenceError: boosted is not defined
    at BOOSTED4_Definition._getOrCreatePopupInstance (ods-charts.js:2229:1)
```

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of ODS Charts are you using?

v0.1.0-alpha.9

**Comment by vogloblinsky** [comment]
+1

**Comment by jacques-lebourgeois** [comment]
I'm closing this bug as it no longer seems relevant. It has probably been solved at [Docs: isolate charts in <iframe>s #173](https://github.com/Orange-OpenSource/ods-charts/pull/173)

**Comment by vogloblinsky** [comment]
Sorry but i think an explanation of Boosted dependency in the documentation is missing.
Just installed last week ODS in my project, and without Boosted, i had to disable `externalizePopover` to make it works

**Comment by jacques-lebourgeois** [comment]
> Sorry but i think an explanation of Boosted dependency in the documentation is missing. Just installed last week ODS in my project, and without Boosted, i had to disable `externalizePopover` to make it works

You're absolutely right, the documentaion is largely perfectible.

Just to be sure, do you use Boosted or not on your project?

Because the library also works without Boosted.

You can use : 
- for graph layout 
  - ODS Charts only
  - Boosted 5
  - Boosted 4 
- to display a popover or tooltip :
  - Apache Echarts rendering customized for ODS by ODS Charts
  - Boosted 4 or 5 rendering

If your problem came from this misunderstanding, the bug is probably more a bug of incomplete documentation.

Let me know,

Thks

**Comment by jacques-lebourgeois** [comment]
So, there is probably a bug, you are right.

In the meantime, you can still use ODS Charts popovers and tooltips by using Apache ECharts and ODS Charts rendering.

To do this, you need to specify the renderer  `ODSChartsPopoverManagers.NONE` as the second parameter of the  `externalizePopover`

```
themeManager.externalizePopover({ }, 
  ODSCharts.ODSChartsPopoverManagers.NONE
);
```
Unfortunately, the documentation doesn't make this very clear. But you can find this setting in the example pages of the [online configurator](https://ods-charts.netlify.app/examples/single-line-chart) by choosing "Apache ECharts rendrerer" as "Popover Renderer"

![Image](https://github.com/user-attachments/assets/feec93f4-eef6-4ef7-938c-dae26b75796a)

**Comment by vogloblinsky** [comment]
Ok nice.
I think it should be mentionned in the main README. It is more clear here. In the API documentation it is also relevant, but the design is more visually cluttered.

**Comment by jacques-lebourgeois** [comment]
NB: the bug is the sme with Boosted 5 

```
ReferenceError: boosted is not defined
    at BOOSTED5_Definition._getOrCreatePopupInstance (ods-chart-popover-definitions.ts:119:1)
```
