### ISSUE TITLE
datazoom not displayed correctly

### ISSUE THREAD

**Issue by JPLucasOrange** [Orange-OpenSource/ods-charts#307]
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/ods-charts/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/ods-charts/blob/main/CONTRIBUTING.md)

### Describe the issue

Sliders are not visibles when using datazoom echarts functionnality

### Reduced test cases

To show the problem, we can run the project angular-boosted-starter and add this to the file "ods-charts.component.ts"
replace line 49 : `tooltip: {},`
by 
    `
tooltip: {
      trigger: 'axis',
      axisPointer: {
        label: {
          formatter: function (params) {
            let oT = new Date(params.value);
            return oT.toLocaleDateString("fr-FR");
          },
        }
      }
    },
    toolbox: {
      feature: {
        dataZoom: {
          yAxisIndex: 'none'
        },
        restore: {},
      }
    },
    dataZoom: [
      {
        type: 'inside',
      },
      {
        type: 'slider',
      }
    ],
`

On this example of echarts, we see slider below the chart to control the zoom :
[apache echarts zoom](https://echarts.apache.org/examples/en/editor.html?c=area-simple&lang=ts&theme=dark&code=DYUwLgBARghgziCBeCBqAdiA7hAIjMEACgEYBOANgA4AaCMugZgEoBuAKFEgHtN8BPZBABMAFggAqCIwoAGWZIgl5sjlwgATAohQBtALodO4TQRhDdAWQIALAHQAnGOg3cAtkWaLG8w-3YAZtwOEETqAJZCJKwQkQA8IiqqsaioXgDe7BAQAG4wIejcOCiYOPiERESwCGgovCACzGxZpoR2AA4ArnA2RLqFWHYA5uAAYp3AwACaIPmedAPD4Ja8YL1eqEoLRUtg5cTM-nYAVtzh6EQA5AD0l00c2VpgMB3dvdZrjtydLpUf9k4XO5PBAALQQWR2ACsXikwgUmyeMF0kXBJH093YAF9_Nx2mBwrwhJlsmBuNxgAT2gAuCAk7IQMAOcJDEYOWmXGAAD3CcEuNBa2Xa3Dg4QJvFpAR-AGNxehQviMoKGQ5wJ0HPLdPjdLJ9HRLsoAKSXPwMiA47JYgWksWgWn07KgAJgDnSkDoQgOfnKwhcl0QS4AGXyIwgAEFVeYAMI2fJgS4tK0tMkUqDcLn25UBWZgdUgTNmx5mABa5LcBcL2X4YZ5cAAki4QBmA4VMAnK0nK6q4GTVfbO4W4DAciAw_W3DARv3lRbzdaIFya7yK6T-O18wHpdohsF-N6zUjaU8QIn59XayvGWuN5c8sBOiB93OWkjS-5abplQ6GWBrxzzqKGiPvOZoziBdLKqu64cnAwDhEBXozi0eotAgzIgHAH5fpBEDoDAbg3qMMAANaIOUMBPmav7QQGcFtuB2RiiAbgAMq_naEGVtk0oUsEHIOEMUBEMIUJQnQADssh0CQjAkMw7aFgOZr5LMbH8Bx35mjxwB8bh2AQCA0qxg4YBwMMTjtDY4TSnYgbnLMDgAOJOBo4TumARBSRCdBeSQdCflxDKaVx3ABAECD-lJOGVtpumXAJQkiWJShQrQEDUPJ0UMkpXHBZWoXheAtJ-VlWm8eyAYJcJokSb5smZYFlpZRiOE5UWzxHmYSHZPo2KsEAA)
![image](https://github.com/user-attachments/assets/525d5530-0f6f-4d96-a28b-6b6070593220)

With ods-charts, we don't see the slider below the graph
![image](https://github.com/user-attachments/assets/2912b933-37f7-4d54-9103-01decc3b4572)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What version of ODS Charts are you using?

0.1.0-alpha.4

**Comment by jacques-lebourgeois** [comment]
Reproduced here : https://codepen.io/jacques-lebourgeois/pen/dyxjgRP

The slider came back when we remove the line 
`echarts.registerTheme(themeManager.name , themeManager.theme);`
